### PR TITLE
Added Italian translation.

### PR DESCRIPTION
**Pull request by MaD70**

### CODE REVIEW

**Comment by ntrel** [comment]
@MaD70 This pull contains two commits before the 'Corrected small typo' one.

**Comment by MaD70** [comment]
@ntrel I accidentally deleted them, I misunderstood the web interface (I'm new to git and github). Does it cause problems?

**Comment by ntrel** [comment]
It's probably OK. But you could edit the title of this pull to say: added Italian translation.

**Comment by MaD70** [comment]
That's right. Done it, thanks.

**Pull request merged**
