### PR TITLE
Credited the V language contributors

### PR DESCRIPTION
**Pull request by MihajloNesic**
There are a lot of community contributions. Give those people some credit too. 
You're all doing a great job.

### CODE REVIEW

**Comment by Serkonda** [comment]
That's a good idea!

**Comment by MihajloNesic** [comment]
> That's a good idea!

Looks like the website changed a lot since I created a PR

**Comment by Serkonda** [comment]
Maybe you could fix the conflicts?

**Comment by MihajloNesic** [comment]
The `Who's behind V?` section has been removed with the website overhaul

**Comment by Serkonda** [comment]
In this case I would close this PR

**Comment by Serkonda** [comment]
This section was moved to the [FAQ](https://github.com/vlang/v/wiki/FAQ)
```
Who's behind V?

Me and 250+ open source contributors.
```

**Comment by MihajloNesic** [comment]
Sounds good to me. The contributors have been credited

**Pull request closed without merging**
