### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by vbrazo**

### CODE REVIEW

**Comment by donnisnoni95** [comment]
@vbrazo  I totally agree with you about this ...

**Comment by vbrazo** [comment]
@donnisnoni95 :)

**Comment by donnisnoni95** [comment]
It's nice if you add this ?? https://github.com/vbrazo/website/pull/1/

**Comment by vbrazo** [comment]
@medvednikov should `vlang/website` have its own `LICENSE`?

**Comment by donnisnoni95** [comment]
Maybe you will consider it

**Pull request closed without merging**
