### PR TITLE
update match & defer docs

### PR DESCRIPTION
**Pull request by joe-conigliaro**
update match & defer docs

### CODE REVIEW

**Comment by iredmail** [comment]
Thank you @joe-conigliaro :)

**Comment by medvednikov** [comment]
Defer doesn't execute a function in V but a block of statements.

**Comment by iredmail** [comment]
Hi Alex, Could you please update the doc with more details?

**Comment by joe-conigliaro** [comment]
is that ok? defer defers the defers, a lot of defers lol

**Comment by medvednikov** [comment]
yes that's better

`of a a block`

`is similar to a switch statement.`

no need in this, there's only match statement.

`It's shorter way `

article missing

` When a matching brach is found`

typo

**Comment by medvednikov** [comment]
@iredmail if you could tell me what you found missing, that would help a lot.

**Comment by joe-conigliaro** [comment]
my bad, fixed it

**Comment by iredmail** [comment]
What I want is:

- explain what defer is used for
- show some serious examples in real world

**Pull request merged**
