### PR TITLE
main.scss: pre { font-size: 11px -> 12px }, for readability

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by ntrel** [comment]
I certainly agree code is too small. But why give any font sizes in absolute pixels? This goes against accessibility. People with eyesight problems will want a much bigger font. We shouldn't override their browser defaults.

**Comment by elimisteve** [comment]
@ntrel Shall I use `em`, then?

**Comment by medvednikov** [comment]
em is better I guess

**Comment by medvednikov** [comment]
Thanks for your contributions @elimisteve and sorry for the delay.

The website now uses translation keys from this repository, so all PRs will be approved within 24 hours from now on, and all changes will be live right away.

**Comment by elimisteve** [comment]
@medvednikov Awesome, thanks! And thank _you_ for your amazing work; V is the best-designed programming language _ever_.

**Pull request merged**
